struct stat;
struct rtcdate;

// system calls
int fork(void);
int exit(int) __attribute__((noreturn));
int wait(int*);
int pipe(int*);
int write(int, const void*, int);
int read(int, void*, int);
int close(int);
int kill(int);
int exec(char*, char**);
int open(const char*, int);
int mknod(const char*, short, short);
int unlink(const char*);
int fstat(int fd, struct stat*);
int link(const char*, const char*);
int mkdir(const char*);
int chdir(const char*);
int dup(int);
int getpid(void);
char* sbrk(int);
int sleep(int);
int uptime(void);
int chmod(const char* path, int mode);
int mkfifo(const char* path, int omode);
void* mmap(void* addr, int length, int prot, int flags, int fd, int offset);
int munmap(void *addr, int length);
int shmget(int key, int size, int shmflg);
void* shmva_get(int id);
int shmclose(int id);
int msgget(int key, int msgflg);
int msgsnd(int id, void* addr, int length);
int msgrcv(int id, void* addr, int size, int type);
int msgclose(int id);
int semget(int initvalue);
int sem_p(int id);
int sem_v(int id);
int semclose(int id);

// ulib.c
int stat(const char*, struct stat*);
char* strcpy(char*, const char*);
void *memmove(void*, const void*, int);
char* strchr(const char*, char c);
int strcmp(const char*, const char*);
void fprintf(int, const char*, ...);
void printf(const char*, ...);
char* gets(char*, int max);
uint strlen(const char*);
void* memset(void*, int, uint);
void* malloc(uint);
void free(void*);
int atoi(const char*);
int memcmp(const void *, const void *, uint);
void *memcpy(void *, const void *, uint);
